name: Build MySQL Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0'
        mysql database: 'test_db'
        mysql root password: 'root_password'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmariadb-dev libcurl4-openssl-dev

    - name: Build plugin
      run: |
        gcc -shared -fPIC -o obb_key_management.so mariadb_plugin.c obb_key_service.c \
        $(mysql_config --cflags) \
        -I/usr/include/mysql -lmysqlclient -lcurl

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mysql-plugin
        path: obb_key_management.so